default:
  outputs:
    dev:
      type: duckdb
      path: "../data/local.duckdb"
      threads: 8
      extensions:
        - httpfs
        - parquet
      settings:
        enable_object_cache: true
        enable_http_metadata_cache: true
        allow_unsigned_extensions: true
      external_root: "../data/"
  target: dev

config:
  send_anonymous_usage_stats: False
  use_colors: True
